version: 0.0
os: linux

files:
  - source: /target/spring-cloud-inegration-0.0.1-SNAPSHOT.jar
    destination: /tmp

#permissions:
 # - object: /
  #  pattern: "**"
   # owner: ec2-user
   # group: ec2-user

hooks:
  ApplicationStop:
      - location: stop-process.sh
        timeout: 180
        runas: root
    ApplicationStart:
      - location: start-process.sh
        timeout: 180
        runas: root