version: 0.0
os: linux

files:
  - source: /spring-cloud-inegration-0.0.1-SNAPSHOT.jar
    destination: /tmp

#permissions:
 # - object: /
  #  pattern: "**"
   # owner: ec2-user
   # group: ec2-user

hooks:
  ApplicationStop:
      - location: /stop.sh
        timeout: 180
        runas: ec2-user
  ApplicationStart:
      - location: /start.sh
        timeout: 180
        runas: ec2-user