version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvnw test
  post_build:
    commands:
      - echo Build Completed on `date`
      - mvnw package
artifacts:
  files:
    - 'target/spring-cloud-inegration-0.0.1-SNAPSHOT.jar'