version: 0.2

phases:
  build:
    commands:
      - eco Build Started on 'date'
      - mvnw test
  post_build:
    commands:
      - eco Build Completed on 'date'
      - mvnw package
artifacts:
  files:
    - 'target/spring-cloud-inegration-0.0.1-SNAPSHOT.jar'