version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
      #- ./gradlew clean build
  post_build:
    commands:
      - echo Build Completed on `date`
      - mvn package
artifacts:
  #files:
    #- 'target/spring-cloud-inegration-0.0.1-SNAPSHOT.jar'
  discard-paths: yes
  files:
    - target/spring-cloud-inegration-0.0.1-SNAPSHOT.jar
    - scripts/start.sh
    - scripts/stop.sh
    - appspec.yml